[package]
name = "my-ideal-prototype"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[features]
default = []
alloc-mimalloc = ["dep:mimalloc"]
alloc-jemalloc = ["dep:tikv-jemallocator"]
uring-single-issuer = []
uring-coop-taskrun = []
uring-defer-taskrun = []

[dependencies]
blake3 = "*"
io-uring = "*"
libc = "*"
mimalloc = { version = "*", optional = true }
openkache-protocol = { version = "*", path = "../protocol" }
quinn = { version = "*", default-features = false, features = ["runtime-tokio", "rustls-aws-lc-rs"] }
rcgen = "*"
rustls = { version = "*", default-features = false, features = ["aws_lc_rs", "prefer-post-quantum", "std"] }
slab = "*"
tikv-jemallocator = { version = "*", optional = true }
tokio = { version = "*", features = ["io-util", "net", "rt", "time"] }

[workspace]
