version: 2
updates:
  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      container-base-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
