#ifndef OPENKACHE_SMITHY_CONTRACT_H
#define OPENKACHE_SMITHY_CONTRACT_H

/* Generated from the OpenKache Smithy contract. Do not edit. */

#include <stdint.h>

#define OPENKACHE_SMITHY_V2_ALPN "openkache/2"
#define OPENKACHE_SMITHY_V2_REQUEST_HEADER_BYTES UINT32_C(9)
#define OPENKACHE_SMITHY_V2_RESPONSE_HEADER_BYTES UINT32_C(5)
#define OPENKACHE_SMITHY_V2_SET_TTL_BYTES UINT32_C(8)
#define OPENKACHE_SMITHY_V2_RESPONSE_VALUE_LENGTH_MASK UINT32_C(1073741823)
#define OPENKACHE_SMITHY_V2_VALUE_COMPRESSED_BIT UINT32_C(2147483648)
#define OPENKACHE_SMITHY_V2_VALUE_ENCRYPTED_BIT UINT32_C(1073741824)
#define OPENKACHE_SMITHY_V2_SET_TTL_BIT UINT32_C(536870912)
#define OPENKACHE_SMITHY_V2_SET_IF_ABSENT_BIT UINT32_C(268435456)
#define OPENKACHE_SMITHY_V2_SET_IF_PRESENT_BIT UINT32_C(134217728)

#define OPENKACHE_SMITHY_V3_ALPN "openkache/1"
#define OPENKACHE_SMITHY_V3_REQUEST_FIXED_BYTES UINT32_C(2)
#define OPENKACHE_SMITHY_V3_RESPONSE_FIXED_BYTES UINT32_C(1)
#define OPENKACHE_SMITHY_V3_MAX_VARUINT_BYTES UINT32_C(9)
#define OPENKACHE_SMITHY_V3_SET_TTL_FLAG UINT8_C(1)
#define OPENKACHE_SMITHY_V3_SET_IF_ABSENT_FLAG UINT8_C(2)
#define OPENKACHE_SMITHY_V3_SET_IF_PRESENT_FLAG UINT8_C(4)
#define OPENKACHE_SMITHY_ITEM_ID_BYTES UINT32_C(32)
#define OPENKACHE_SMITHY_MAX_VALUE_BYTES UINT32_C(67108864)

#define OPENKACHE_SMITHY_VALUE_FORMAT_VERSION UINT32_C(1)
#define OPENKACHE_SMITHY_VALUE_FORMAT_MAX_VU128_BYTES UINT32_C(17)
#define OPENKACHE_SMITHY_VALUE_FORMAT_FORMAT_BYTE_BYTES UINT32_C(1)
#define OPENKACHE_SMITHY_VALUE_FORMAT_COMPRESSION_MASK UINT8_C(15)
#define OPENKACHE_SMITHY_VALUE_FORMAT_ENCRYPTION_SHIFT UINT8_C(4)
#define OPENKACHE_SMITHY_VALUE_FORMAT_SERIALIZATION_RAW UINT8_C(0)
#define OPENKACHE_SMITHY_VALUE_FORMAT_SERIALIZATION_JSON UINT8_C(1)
#define OPENKACHE_SMITHY_VALUE_FORMAT_COMPRESSION_NONE UINT8_C(0)
#define OPENKACHE_SMITHY_VALUE_FORMAT_COMPRESSION_ZSTANDARD UINT8_C(1)
#define OPENKACHE_SMITHY_VALUE_FORMAT_ENCRYPTION_NONE UINT8_C(0)
#define OPENKACHE_SMITHY_VALUE_FORMAT_ENCRYPTION_COMPACT UINT8_C(1)
#define OPENKACHE_SMITHY_VALUE_FORMAT_ENCRYPTION_ROBUST UINT8_C(2)
#define OPENKACHE_SMITHY_VALUE_FORMAT_COMPACT_SYNTHETIC_IV_BYTES UINT32_C(16)
#define OPENKACHE_SMITHY_VALUE_FORMAT_ROBUST_NONCE_BYTES UINT32_C(12)
#define OPENKACHE_SMITHY_VALUE_FORMAT_ROBUST_TAG_BYTES UINT32_C(16)
#define OPENKACHE_SMITHY_VALUE_FORMAT_DATA_PROTECTION_KEY_BYTES UINT32_C(32)
#define OPENKACHE_SMITHY_VALUE_FORMAT_ITEM_ID_ROOT_CONTEXT "OpenKache client item key root v1"
#define OPENKACHE_SMITHY_VALUE_FORMAT_AAD_DOMAIN "openkache/value-format/aad/v1"
#define OPENKACHE_SMITHY_VALUE_FORMAT_VALUE_ROOT_CONTEXT "OpenKache value format v1 root key"
#define OPENKACHE_SMITHY_VALUE_FORMAT_COMPACT_MAC_CONTEXT "OpenKache value format v1 AES-256-SIV-CMAC MAC key"
#define OPENKACHE_SMITHY_VALUE_FORMAT_COMPACT_ENCRYPTION_CONTEXT "OpenKache value format v1 AES-256-SIV-CMAC encryption key"
#define OPENKACHE_SMITHY_VALUE_FORMAT_ROBUST_CONTEXT "OpenKache value format v1 AES-256-GCM-SIV key"
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_AND_VERSION_0 UINT8_C(79)
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_AND_VERSION_1 UINT8_C(75)
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_AND_VERSION_2 UINT8_C(86)
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_AND_VERSION_3 UINT8_C(1)
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAX_ENCODING_BYTES UINT32_C(64)
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAX_TYPE_NAME_BYTES UINT32_C(65535)
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_JSON_ENCODING "json"

#define OPENKACHE_SMITHY_OPERATION_PING UINT32_C(1)
#define OPENKACHE_SMITHY_OPERATION_GET UINT32_C(2)
#define OPENKACHE_SMITHY_OPERATION_SET UINT32_C(3)
#define OPENKACHE_SMITHY_OPERATION_DELETE UINT32_C(4)
#define OPENKACHE_SMITHY_OPERATION_STATS UINT32_C(5)
#define OPENKACHE_SMITHY_OPERATION_SYNC UINT32_C(6)
#define OPENKACHE_SMITHY_STATUS_OK UINT8_C(0)
#define OPENKACHE_SMITHY_STATUS_NOT_FOUND UINT8_C(1)
#define OPENKACHE_SMITHY_STATUS_CREATED UINT8_C(2)
#define OPENKACHE_SMITHY_STATUS_REPLACED UINT8_C(3)
#define OPENKACHE_SMITHY_STATUS_DELETED UINT8_C(4)
#define OPENKACHE_SMITHY_STATUS_NOT_STORED UINT8_C(5)
#define OPENKACHE_SMITHY_STATUS_INVALID_REQUEST UINT8_C(64)
#define OPENKACHE_SMITHY_STATUS_UNSUPPORTED_OPCODE UINT8_C(65)
#define OPENKACHE_SMITHY_STATUS_TOO_LARGE UINT8_C(66)
#define OPENKACHE_SMITHY_STATUS_OVERLOADED UINT8_C(67)
#define OPENKACHE_SMITHY_STATUS_TIMEOUT UINT8_C(68)
#define OPENKACHE_SMITHY_STATUS_FORBIDDEN UINT8_C(69)
#define OPENKACHE_SMITHY_STATUS_INTERNAL_ERROR UINT8_C(127)

#define OPENKACHE_SMITHY_ABI_VERSION UINT32_C(1)
#define OPENKACHE_SMITHY_OPERATION_RECONNECT UINT32_C(4294967041)
#define OPENKACHE_SMITHY_OPERATION_CONNECTION_STATE UINT32_C(4294967042)
#define OPENKACHE_SMITHY_RESULT_ERROR UINT32_C(0)
#define OPENKACHE_SMITHY_RESULT_OK UINT32_C(1)
#define OPENKACHE_SMITHY_RESULT_VALUE UINT32_C(2)
#define OPENKACHE_SMITHY_RESULT_NOT_FOUND UINT32_C(3)
#define OPENKACHE_SMITHY_RESULT_CREATED UINT32_C(4)
#define OPENKACHE_SMITHY_RESULT_REPLACED UINT32_C(5)
#define OPENKACHE_SMITHY_RESULT_DELETED UINT32_C(6)
#define OPENKACHE_SMITHY_RESULT_NOT_DELETED UINT32_C(7)
#define OPENKACHE_SMITHY_RESULT_CONNECTED UINT32_C(8)
#define OPENKACHE_SMITHY_RESULT_NOT_STORED UINT32_C(9)
#define OPENKACHE_SMITHY_RESULT_CONNECTION_STATE UINT32_C(10)
#define OPENKACHE_SMITHY_SET_CONDITION_NONE UINT32_C(0)
#define OPENKACHE_SMITHY_SET_CONDITION_IF_ABSENT UINT32_C(1)
#define OPENKACHE_SMITHY_SET_CONDITION_IF_PRESENT UINT32_C(2)
#define OPENKACHE_SMITHY_CONNECTION_STATE_CONNECTED UINT8_C(0)
#define OPENKACHE_SMITHY_CONNECTION_STATE_RECONNECTING UINT8_C(1)
#define OPENKACHE_SMITHY_CONNECTION_STATE_DISCONNECTED UINT8_C(2)
#define OPENKACHE_SMITHY_CONNECTION_STATE_CLOSED UINT8_C(3)
#define OPENKACHE_SMITHY_CONNECTION_STATE_UNKNOWN UINT8_C(4)

#endif /* OPENKACHE_SMITHY_CONTRACT_H */
