/* Generated from the OpenKache Smithy contract. Do not edit. */
#ifndef OPENKACHE_SMITHY_CONTRACT_H
#define OPENKACHE_SMITHY_CONTRACT_H

#include <stdint.h>

#define OPENKACHE_SMITHY_ITEM_ID_BYTES 32u
#define OPENKACHE_SMITHY_MAX_VALUE_BYTES 67108864u
#define OPENKACHE_SMITHY_ALPN "openkache/1"
#define OPENKACHE_SMITHY_VALUE_FORMAT_VERSION 1u
#define OPENKACHE_SMITHY_VALUE_FORMAT_MAX_VU128_BYTES 17u
#define OPENKACHE_SMITHY_VALUE_FORMAT_FORMAT_BYTE_BYTES 1u
#define OPENKACHE_SMITHY_VALUE_FORMAT_COMPRESSION_MASK 0x0fu
#define OPENKACHE_SMITHY_VALUE_FORMAT_ENCRYPTION_SHIFT 0x04u
#define OPENKACHE_SMITHY_VALUE_SERIALIZATION_RAW 0x00u
#define OPENKACHE_SMITHY_VALUE_SERIALIZATION_JSON 0x01u
#define OPENKACHE_SMITHY_VALUE_COMPRESSION_NONE 0x00u
#define OPENKACHE_SMITHY_VALUE_COMPRESSION_ZSTANDARD 0x01u
#define OPENKACHE_SMITHY_VALUE_ENCRYPTION_NONE 0x00u
#define OPENKACHE_SMITHY_VALUE_ENCRYPTION_COMPACT 0x01u
#define OPENKACHE_SMITHY_VALUE_ENCRYPTION_ROBUST 0x02u
#define OPENKACHE_SMITHY_VALUE_COMPACT_SYNTHETIC_IV_BYTES 16u
#define OPENKACHE_SMITHY_VALUE_ROBUST_NONCE_BYTES 12u
#define OPENKACHE_SMITHY_VALUE_ROBUST_TAG_BYTES 16u
#define OPENKACHE_SMITHY_VALUE_DATA_PROTECTION_KEY_BYTES 32u
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAX_ENCODING_BYTES 64u
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAX_TYPE_NAME_BYTES 65535u

typedef enum openkache_smithy_opcode {
    OPENKACHE_SMITHY_OPCODE_PING = 0x01,
    OPENKACHE_SMITHY_OPCODE_GET = 0x02,
    OPENKACHE_SMITHY_OPCODE_SET = 0x03,
    OPENKACHE_SMITHY_OPCODE_DELETE = 0x04,
    OPENKACHE_SMITHY_OPCODE_STATS = 0x05,
    OPENKACHE_SMITHY_OPCODE_SYNC = 0x06,
} openkache_smithy_opcode;

typedef enum openkache_smithy_status {
    OPENKACHE_SMITHY_STATUS_OK = 0x00,
    OPENKACHE_SMITHY_STATUS_NOT_FOUND = 0x01,
    OPENKACHE_SMITHY_STATUS_CREATED = 0x02,
    OPENKACHE_SMITHY_STATUS_REPLACED = 0x03,
    OPENKACHE_SMITHY_STATUS_DELETED = 0x04,
    OPENKACHE_SMITHY_STATUS_NOT_STORED = 0x05,
    OPENKACHE_SMITHY_STATUS_INVALID_REQUEST = 0x40,
    OPENKACHE_SMITHY_STATUS_UNSUPPORTED_OPCODE = 0x41,
    OPENKACHE_SMITHY_STATUS_TOO_LARGE = 0x42,
    OPENKACHE_SMITHY_STATUS_OVERLOADED = 0x43,
    OPENKACHE_SMITHY_STATUS_TIMEOUT = 0x44,
    OPENKACHE_SMITHY_STATUS_FORBIDDEN = 0x45,
    OPENKACHE_SMITHY_STATUS_INTERNAL_ERROR = 0x7f,
} openkache_smithy_status;

/* Smithy string-enum values used by the language-neutral set API. */
#define OPENKACHE_SMITHY_SET_CONDITION_IF_ABSENT "if_absent"
#define OPENKACHE_SMITHY_SET_CONDITION_IF_PRESENT "if_present"
#define OPENKACHE_SMITHY_SET_OUTCOME_CREATED "created"
#define OPENKACHE_SMITHY_SET_OUTCOME_REPLACED "replaced"
#define OPENKACHE_SMITHY_SET_OUTCOME_NOT_STORED "not_stored"

/* Four-byte legacy value-envelope magic, in wire order. */
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_0 0x4fu
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_1 0x4bu
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_2 0x56u
#define OPENKACHE_SMITHY_VALUE_ENVELOPE_MAGIC_3 0x01u

#endif
