[package]
name = "openkache-client-napi"
version = "0.1.0"
edition = "2024"
description = "Node-API adapter for the OpenKache Rust client"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures-util = "*"
napi = { version = "*", default-features = false, features = ["async", "napi8", "serde-json"] }
napi-derive = "*"
openkache-client-core = { path = "../../core", default-features = false, features = ["quic-quinn"] }
serde_json = "*"

[build-dependencies]
napi-build = "*"
