<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>OpenKache</PackageId>
    <Version>0.1.0</Version>
    <Authors>OpenKache Team</Authors>
    <Description>Managed QUIC client for the OpenKache binary protocol</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://openkache.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/openkache/openkache</RepositoryUrl>
    <PackageTags>cache;openkache;ssd;redis;kv;client</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
