[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-unknown-linux-gnu]
linker = "clang"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-unknown-linux-musl-clang"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-unknown-linux-musl-clang"

[alias]
server-build = [
  "build",
  "--locked",
  "--release",
  "--package",
  "openkache-server",
  "--bin",
  "openkache-server",
]
