[package]
name = "openkache-client"
version = "0.1.0"
edition.workspace = true
description = "Ergonomic Rust client for the OpenKache cache server"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/openkache/openkache"
homepage = "https://openkache.com"
documentation = "https://docs.rs/openkache-client"
keywords = ["cache", "client", "quic", "tls", "openkache"]
categories = ["network-programming", "database"]
rust-version = "1.85"
include = [
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "build.rs",
    "src/**/*.rs",
    "examples/**/*.rs",
]

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["quic-quinn", "runtime-tokio"]
ffi = ["openkache-client-core/ffi"]
quic-compio = ["openkache-client-core/quic-compio"]
quic-quinn = ["openkache-client-core/quic-quinn"]
runtime-tokio = ["dep:tokio"]
tls-tcp = ["openkache-client-core/tls-tcp"]

[dependencies]
openkache-client-core = { version = "*", path = "../core", default-features = false }
tokio = { version = "*", features = ["macros", "rt-multi-thread"], optional = true }
