//! Protocol-v1 compatibility projections.
//!
//! These constants and direct field indexes support the historical public API
//! facade. Exact request framing itself is generated by the canonical
//! operation contract. Compact optional-value symbols are re-exported as a
//! source-compatible facade; the codec itself is shared by generated layouts.

mod generated {
    include!(concat!(env!("OUT_DIR"), "/operation_compatibility.rs"));
}

/// Historical compact request route selected by a protocol-v1 adapter.
///
/// The route vocabulary and opcode projection are generated from explicit
/// compatibility metadata. This module only exposes the adapter-facing alias;
/// generic operation metadata never needs to import it.
pub use generated::{
    response_budget, response_framing, CompatibilityResponseFraming, RESPONSE_BUDGETS,
    RESPONSE_FRAMINGS,
    DELETE_FLAGS_BYTES, DELETE_IF_EMPTY, DELETE_MODE_MASK, DELETE_RESERVED_MASK,
    MAX_COMPATIBILITY_REQUEST_FRAME_BYTES, NAMESPACE_NAME_MAX_BYTES, OPEN_CREATE_IF_MISSING,
    OPEN_FLAGS_BYTES, OPEN_RESERVED_MASK, POLICY_DEFAULT_EXPIRATION_MASK,
    POLICY_DEFAULT_EXPIRATION_RESERVED_BITS,
    POLICY_EVICTION_OVERRIDE, POLICY_EVICTION_PROTECTED, POLICY_EXPIRATION_OVERRIDE,
    POLICY_FIXED_TTL, POLICY_FLAGS_BYTES, POLICY_NO_EXPIRY, POLICY_RESERVED_MASK,
    SET_CONDITION_ANY_BITS, SET_CONDITION_MASK, SET_CONDITION_RESERVED_BITS, SET_EVICTABLE_BITS,
    SET_EVICTION_MASK, SET_EVICTION_PROTECTED_BITS, SET_EVICTION_RESERVED_BITS,
    SET_EXPIRATION_MASK, SET_EXPIRATION_RESERVED_BITS, SET_EXPLICIT_TTL_BITS, SET_FLAGS_BYTES,
    SET_IF_ABSENT_BITS, SET_IF_PRESENT_BITS, SET_INHERIT_EVICTION_BITS,
    SET_INHERIT_EXPIRATION_BITS, SET_NO_EXPIRY_BITS, SET_RESERVED_MASK, request_fields,
    request_projection, response_fields,
};

// Keep these names available through the v1 facade for compatibility clients.
pub use crate::optional_values::{
    optional_value_prefix, OptionalValues, OptionalValuesEncoder, OPTIONAL_VALUE_LENGTH_BYTES,
    OPTIONAL_VALUE_MISSING, decode_optional_values, encode_optional_values,
    optional_values_encoded_len, optional_values_encoded_len_from_lengths,
    optional_values_max_encoded_len,
};
