//! Draft-v1 compact policy and flag constants.
//!
//! Request layouts and field indexes come from the canonical operation
//! contract. These adapter-owned values remain separate so new operations do
//! not acquire policy or flag vocabulary.

mod generated {
    include!(concat!(env!("OUT_DIR"), "/operation_compatibility.rs"));
}

pub use generated::{
    DELETE_FLAGS_BYTES, DELETE_IF_EMPTY, DELETE_MODE_MASK, DELETE_RESERVED_MASK,
    NAMESPACE_NAME_MAX_BYTES, OPEN_CREATE_IF_MISSING, OPEN_FLAGS_BYTES, OPEN_RESERVED_MASK,
    POLICY_DEFAULT_EXPIRATION_MASK, POLICY_DEFAULT_EXPIRATION_RESERVED_BITS,
    POLICY_EVICTION_OVERRIDE, POLICY_EVICTION_PROTECTED, POLICY_EXPIRATION_OVERRIDE,
    POLICY_FIXED_TTL, POLICY_FLAGS_BYTES, POLICY_NO_EXPIRY, POLICY_RESERVED_MASK,
    SET_CONDITION_ANY_BITS, SET_CONDITION_MASK, SET_CONDITION_RESERVED_BITS, SET_EVICTABLE_BITS,
    SET_EVICTION_MASK, SET_EVICTION_PROTECTED_BITS, SET_EVICTION_RESERVED_BITS,
    SET_EXPIRATION_MASK, SET_EXPIRATION_RESERVED_BITS, SET_EXPLICIT_TTL_BITS, SET_FLAGS_BYTES,
    SET_IF_ABSENT_BITS, SET_IF_PRESENT_BITS, SET_INHERIT_EVICTION_BITS,
    SET_INHERIT_EXPIRATION_BITS, SET_NO_EXPIRY_BITS, SET_RESERVED_MASK,
};
