//! Server protocol framing and cache policy values.

pub use crate::contract::{WireRequestLayout, WireRequestStep, wire_request_layout};
pub use openkache_protocol::{ItemId, Opcode, Response, Status};
use openkache_protocol::{
    MAX_VARUINT_BYTES, NAMESPACE_ID_BYTES, REQUEST_FIXED_BYTES, RequestFrameHeader,
};

type WireResult<T> = openkache_protocol::Result<T>;

#[path = "protocol_policy.rs"]
mod policy;
#[path = "protocol_policy_codec.rs"]
mod policy_codec;
pub use policy::{
    EvictionDefault, EvictionMode, ExpirationDefault, ExpirationMode, NamespaceDescriptor,
    NamespacePolicy, OverridePolicy, SetCondition, SetOptions,
};

/// Returns the complete generated request-frame admission ceiling.
pub(crate) const fn max_request_frame_bytes() -> usize {
    crate::operation_contract::MAX_REQUEST_FRAME_BYTES
}

/// A complete request viewed as an opaque operation call.
///
/// The server adapter supplies generated byte-consumption metadata to the
/// operation-neutral parser. It deliberately does not decode application
/// fields or operation semantics.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RequestFrame<'a> {
    inner: openkache_protocol::OpaqueRequestFrame<'a>,
}

impl<'a> RequestFrame<'a> {
    fn layout(prefix: &[u8]) -> WireResult<Option<WireRequestLayout>> {
        let Some(&opcode_byte) = prefix.first() else {
            return Ok(None);
        };
        let opcode = Opcode::try_from(opcode_byte)?;
        Ok(Some(wire_request_layout(opcode)))
    }

    /// Decodes only the frame metadata needed to delimit one request.
    pub fn decode_header(prefix: &[u8]) -> WireResult<Option<RequestFrameHeader>> {
        let Some(layout) = Self::layout(prefix)? else {
            return Ok(None);
        };
        openkache_protocol::OpaqueRequestFrame::decode_header(prefix, layout)
    }

    /// Returns the exact additional bytes needed to complete the next
    /// unresolved request-header step.
    pub fn header_bytes_needed(prefix: &[u8]) -> WireResult<usize> {
        let Some(layout) = Self::layout(prefix)? else {
            return Ok(REQUEST_FIXED_BYTES - prefix.len());
        };
        openkache_protocol::OpaqueRequestFrame::header_bytes_needed(prefix, layout)
    }

    /// Reports the complete frame length once enough metadata is available.
    pub fn frame_len(prefix: &[u8]) -> WireResult<Option<usize>> {
        Self::decode_header(prefix)?
            .map(RequestFrameHeader::frame_len)
            .transpose()
    }

    /// Decodes one complete request without interpreting its operation body.
    ///
    /// # Errors
    ///
    /// Returns a protocol error when the opcode, generated wire layout, or
    /// complete frame length is invalid.
    pub fn decode(frame: &'a [u8]) -> WireResult<Self> {
        let layout =
            Self::layout(frame)?.ok_or(openkache_protocol::ProtocolError::FrameTooShort {
                expected: REQUEST_FIXED_BYTES,
                actual: frame.len(),
            })?;
        Ok(Self {
            inner: openkache_protocol::OpaqueRequestFrame::decode(frame, layout)?,
        })
    }

    /// Returns the operation discriminator.
    pub const fn opcode(self) -> Opcode {
        self.inner.opcode()
    }

    /// Returns the opaque operation body after the opcode.
    pub fn body(self) -> &'a [u8] {
        self.inner.body()
    }

    /// Returns the original complete encoded frame.
    pub const fn encoded(self) -> &'a [u8] {
        self.inner.encoded()
    }
}

fn read_u64_be(input: &[u8]) -> Result<u64> {
    let bytes: [u8; NAMESPACE_ID_BYTES] = input
        .get(..NAMESPACE_ID_BYTES)
        .ok_or(ProtocolError::FrameTooShort {
            expected: NAMESPACE_ID_BYTES,
            actual: input.len(),
        })?
        .try_into()
        .expect("slice length checked");
    Ok(u64::from_be_bytes(bytes))
}

fn encode_varuint(value: u64) -> ([u8; MAX_VARUINT_BYTES], usize) {
    openkache_protocol::encode_varuint(value)
}

fn decode_varuint(input: &[u8], context: &'static str) -> Result<Option<(u64, usize)>> {
    openkache_protocol::decode_varuint(input, context).map_err(Into::into)
}

/// Policy framing and validation errors.
#[derive(Debug, thiserror::Error)]
pub enum ProtocolError {
    #[error("unknown opcode 0x{0:02x}")]
    UnknownOpcode(u8),
    #[error("unknown status 0x{0:02x}")]
    UnknownStatus(u8),
    #[error("request flags contain unknown bits 0x{0:02x}")]
    UnknownRequestFlags(u8),
    #[error("frame is too short: expected at least {expected} bytes, got {actual}")]
    FrameTooShort { expected: usize, actual: usize },
    #[error("frame length does not match header: expected {expected} bytes, got {actual}")]
    FrameLength { expected: usize, actual: usize },
    #[error("frame length overflow")]
    FrameLengthOverflow,
    #[error("{context} uses a non-canonical vu128 encoding")]
    NonCanonicalVaruint { context: &'static str },
    #[error("{context} exceeds the supported 64-bit vu128 range")]
    VaruintOverflow { context: &'static str },
    #[error("value is too large: {size} bytes exceeds {maximum}")]
    ValueTooLarge { size: usize, maximum: usize },
    #[error("item ID has {actual} bytes; maximum is {maximum}")]
    InvalidItemIdLength { maximum: usize, actual: usize },
    #[error("request packed byte at offset {offset} violates its bit contract")]
    InvalidRequestPackedBits { offset: usize },
    #[error("request constant does not match at offset {offset}")]
    RequestConstantMismatch { offset: usize },
    #[error("optional-value payload is invalid: {0}")]
    InvalidOptionalValues(&'static str),
    #[error("operation field sequence is invalid: {0}")]
    InvalidFieldSequence(&'static str),
    #[error("if-absent and if-present conditions cannot be combined")]
    ConflictingSetConditions,
    #[error("SET TTL must be greater than zero milliseconds")]
    InvalidSetTtl,
    #[error("SET TTL is required by ExplicitTtl")]
    MissingSetTtl,
    #[error("SET TTL is not allowed by this expiration mode")]
    UnexpectedSetTtl,
    #[error("SET options are not valid for {opcode:?}")]
    InvalidSetOptions { opcode: Opcode },
    #[error("namespace ID must be a positive non-zero u64")]
    InvalidNamespaceId,
    #[error("namespace policy is missing")]
    MissingNamespacePolicy,
    #[error("namespace policy is invalid: {0}")]
    InvalidNamespacePolicy(&'static str),
    #[error("namespace revision must be positive")]
    InvalidRevision,
}

impl From<openkache_protocol::ProtocolError> for ProtocolError {
    fn from(error: openkache_protocol::ProtocolError) -> Self {
        match error {
            openkache_protocol::ProtocolError::UnknownOpcode(value) => Self::UnknownOpcode(value),
            openkache_protocol::ProtocolError::UnknownStatus(value) => Self::UnknownStatus(value),
            openkache_protocol::ProtocolError::FrameTooShort { expected, actual } => {
                Self::FrameTooShort { expected, actual }
            }
            openkache_protocol::ProtocolError::FrameLength { expected, actual } => {
                Self::FrameLength { expected, actual }
            }
            openkache_protocol::ProtocolError::FrameLengthOverflow => Self::FrameLengthOverflow,
            openkache_protocol::ProtocolError::NonCanonicalVaruint { context } => {
                Self::NonCanonicalVaruint { context }
            }
            openkache_protocol::ProtocolError::VaruintOverflow { context } => {
                Self::VaruintOverflow { context }
            }
            openkache_protocol::ProtocolError::ValueTooLarge { size, maximum } => {
                Self::ValueTooLarge { size, maximum }
            }
            openkache_protocol::ProtocolError::InvalidItemIdLength { maximum, actual } => {
                Self::InvalidItemIdLength { maximum, actual }
            }
            openkache_protocol::ProtocolError::InvalidRequestPackedBits { offset } => {
                Self::InvalidRequestPackedBits { offset }
            }
            openkache_protocol::ProtocolError::RequestConstantMismatch { offset } => {
                Self::RequestConstantMismatch { offset }
            }
            openkache_protocol::ProtocolError::InvalidOptionalValues(message) => {
                Self::InvalidOptionalValues(message)
            }
            openkache_protocol::ProtocolError::InvalidFieldSequence(message) => {
                Self::InvalidFieldSequence(message)
            }
        }
    }
}

/// Convenience result type for policy operations.
pub type Result<T> = std::result::Result<T, ProtocolError>;
