//! Operation-neutral request framing and transport-owned request envelopes.

use super::{
    FrameLayoutProvider, Opcode, REQUEST_FIXED_BYTES, WireRequestLayout, WireResult,
    DEFAULT_FRAME_LAYOUT_PROVIDER,
};
use openkache_protocol::{OwnedRange, RequestFrameHeader};

/// A complete request viewed as an opaque operation call.
///
/// The server adapter supplies generated byte-consumption metadata to the
/// operation-neutral parser. It deliberately does not decode namespace IDs,
/// item IDs, values, or operation semantics.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RequestFrame<'a> {
    inner: openkache_protocol::OpaqueRequestFrame<'a>,
}

impl<'a> RequestFrame<'a> {
    fn layout_with<P: FrameLayoutProvider + ?Sized>(
        prefix: &[u8],
        provider: &P,
    ) -> WireResult<Option<WireRequestLayout>> {
        let Some(&opcode_byte) = prefix.first() else {
            return Ok(None);
        };
        let opcode = Opcode::try_from(opcode_byte)?;
        let layout = provider.layout_for(opcode)?;
        Ok(Some(layout))
    }

    /// Decodes only the frame metadata needed to delimit one request.
    pub fn decode_header(prefix: &[u8]) -> WireResult<Option<RequestFrameHeader>> {
        Self::decode_header_with(prefix, &DEFAULT_FRAME_LAYOUT_PROVIDER)
    }

    /// Decodes frame metadata with an explicitly selected layout provider.
    pub(crate) fn decode_header_with<P: FrameLayoutProvider + ?Sized>(
        prefix: &[u8],
        provider: &P,
    ) -> WireResult<Option<RequestFrameHeader>> {
        let Some(layout) = Self::layout_with(prefix, provider)? else {
            return Ok(None);
        };
        openkache_protocol::OpaqueRequestFrame::decode_header(prefix, layout)
    }

    /// Returns the exact additional metadata bound for an explicitly selected
    /// layout provider.
    pub(crate) fn header_bytes_needed_with<P: FrameLayoutProvider + ?Sized>(
        prefix: &[u8],
        provider: &P,
    ) -> WireResult<usize> {
        let Some(layout) = Self::layout_with(prefix, provider)? else {
            return Ok(1);
        };
        openkache_protocol::OpaqueRequestFrame::header_bytes_needed(prefix, layout)
    }

    /// Reports the complete frame length once enough metadata is available.
    pub fn frame_len(prefix: &[u8]) -> WireResult<Option<usize>> {
        Self::frame_len_with(prefix, &DEFAULT_FRAME_LAYOUT_PROVIDER)
    }

    /// Reports frame length with an explicitly selected layout provider.
    pub(crate) fn frame_len_with<P: FrameLayoutProvider + ?Sized>(
        prefix: &[u8],
        provider: &P,
    ) -> WireResult<Option<usize>> {
        Self::decode_header_with(prefix, provider)?
            .map(RequestFrameHeader::frame_len)
            .transpose()
    }

    /// Decodes one complete request without interpreting its operation body.
    ///
    /// # Errors
    ///
    /// Returns a protocol error when the opcode, generated wire layout, or
    /// complete frame length is invalid.
    pub fn decode(frame: &'a [u8]) -> WireResult<Self> {
        Self::decode_with(frame, &DEFAULT_FRAME_LAYOUT_PROVIDER)
    }

    /// Decodes one complete request with an explicitly selected layout
    /// provider.
    pub(crate) fn decode_with<P: FrameLayoutProvider + ?Sized>(
        frame: &'a [u8],
        provider: &P,
    ) -> WireResult<Self> {
        let layout = Self::layout_with(frame, provider)?.ok_or(
            openkache_protocol::ProtocolError::FrameTooShort {
                expected: REQUEST_FIXED_BYTES,
                actual: frame.len(),
            },
        )?;
        Ok(Self {
            inner: openkache_protocol::OpaqueRequestFrame::decode(frame, layout)?,
        })
    }

    /// Returns the operation discriminator.
    pub const fn opcode(self) -> Opcode {
        self.inner.opcode()
    }

    /// Returns the opaque operation body after the opcode.
    pub fn body(self) -> &'a [u8] {
        self.inner.body()
    }

    /// Returns the original complete encoded frame.
    pub const fn encoded(self) -> &'a [u8] {
        self.inner.encoded()
    }
}

/// One transport-owned request passed to every API decoder.
///
/// Prefix and payload ownership are retained independently. The envelope does
/// not classify the operation by wire family or materialize a semantic
/// request; generated or API-owned field projection happens only after
/// registration selects the decoder.
pub(crate) struct ServerRequest {
    opcode: Opcode,
    prefix: Vec<u8>,
    payload: OwnedRange,
}

impl ServerRequest {
    pub(super) fn new(opcode: Opcode, prefix: Vec<u8>, payload: OwnedRange) -> Self {
        Self {
            opcode,
            prefix,
            payload,
        }
    }

    pub(crate) const fn opcode(&self) -> Opcode {
        self.opcode
    }

    /// Moves the retained payload into a generated field view.
    pub(crate) fn into_payload(self) -> (Opcode, OwnedRange) {
        (self.opcode, self.payload)
    }

    /// Moves the complete retained wire parts into the generated request-plan
    /// decoder.
    pub(crate) fn into_wire_parts(self) -> (Opcode, Vec<u8>, OwnedRange) {
        (self.opcode, self.prefix, self.payload)
    }
}
