name: Publish NuGet

on:
  push:
    branches: [main]
    paths: ["clients/dotnet/**"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x
      - uses: ./.github/actions/setup-smithy-codegen
      - run: dotnet pack clients/dotnet/OpenKache/OpenKache.csproj -c Release -o out
      - uses: NuGet/login@v1
        id: nugetlogin
        with:
          user: kkimdev
      - run: dotnet nuget push out/*.nupkg --api-key "${{ steps.nugetlogin.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
